# Generated by Django 3.2.5 on 2021-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('blog', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='image/')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
