# Generated by Django 2.0.13 on 2021-07-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
