# Generated by Django 2.0.13 on 2021-07-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='img',
        ),
    ]
