# Generated by Django 2.0.13 on 2021-07-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210728_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
