# Generated by Django 2.0.13 on 2021-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210730_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(),
        ),
    ]
